routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Auth::routes();
/* CoreUI templates */

Route::middleware('auth')->group(function ()
{
    Route::resource('/', 'DashboardController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('document_management', 'Document\DocumentManagementController');
    Route::resource('document_planning', 'Document\DocumentPlanningController');
    Route::resource('document_request', 'Document\DocumentRequestController');
    Route::resource('document_request_district', 'Document\DocumentRequestDistrictController');
    Route::resource('document_approval', 'Document\DocumentApprovalController');
    Route::resource('document_approval_district', 'Document\DocumentApprovalDistrictController');
    Route::resource('document_delivery_pre_census', 'Document\DocumentDeliveryPreCensusController');
    Route::resource('document_delivery_post_census', 'Document\DocumentDeliveryPostCensusController');
    Route::resource('document_acceptance_pre_census', 'Document\DocumentAcceptancePreCensusController');
    Route::resource('document_acceptance_post_census', 'Document\DocumentAcceptancePostCensusController');
    Route::resource('document_store_record', 'Document\DocumentStoreRecordController');
    Route::resource('document_tracking', 'Document\DocumentTrackingController');
    Route::resource('document_tracking_state', 'Document\DocumentTrackingStateController');
    Route::resource('document_tracking_district_admin', 'Document\DocumentTrackingDistrictAdminController');
    Route::resource('document_tracking_district', 'Document\DocumentTrackingDistrictController');
    Route::resource('document_tracking_eb', 'Document\DocumentTrackingEBController');
    Route::resource('document_tracking_acceptance', 'Document\DocumentTrackingAcceptanceController');



    Route::resource('vendor_dashboard', 'Vendor\VendorDashboardController');
    Route::resource('vendor_list', 'Vendor\VendorListController');
    Route::resource('vendor_management', 'Vendor\VendorManagementController');
    Route::resource('vendor_management_btype', 'Vendor\VendorManagementBTypeController');

    Route::resource('asset_management', 'Asset\AssetManagementController');
    Route::resource('asset_planning', 'Asset\AssetPlanningController');
    Route::resource('asset_request', 'Asset\AssetRequestController');
    Route::resource('asset_request_district', 'Asset\AssetRequestDistrictController');
    Route::resource('asset_approval', 'Asset\AssetApprovalController');
    Route::resource('asset_approval_district', 'Asset\AssetApprovalDistrictController');
    Route::resource('asset_delivery_pre_census', 'Asset\AssetDeliveryPreCensusController');
    Route::resource('asset_delivery_post_census', 'Asset\AssetDeliveryPostCensusController');
    Route::resource('asset_acceptance_pre_census', 'Asset\AssetAcceptancePreCensusController');
    Route::resource('asset_acceptance_post_census', 'Asset\AssetAcceptancePostCensusController');
    Route::resource('asset_store_record', 'Asset\AssetStoreRecordController');
    Route::resource('asset_tracking', 'Asset\AssetTrackingController');
    Route::resource('asset_tracking_state', 'Asset\AssetTrackingStateController');
    Route::resource('asset_tracking_district_admin', 'Asset\AssetTrackingDistrictAdminController');
    Route::resource('asset_tracking_district', 'Asset\AssetTrackingDistrictController');
    Route::resource('asset_tracking_eb', 'Asset\AssetTrackingEBController');
    Route::resource('asset_tracking_acceptance', 'Asset\AssetTrackingAcceptanceController');

    Route::resource('inventory_management', 'Inventory\InventoryManagementController');
    Route::resource('inventory_planning', 'Inventory\InventoryPlanningController');
    Route::resource('inventory_request', 'Inventory\InventoryRequestController');
    Route::resource('inventory_request_district', 'Inventory\InventoryRequestDistrictController');
    Route::resource('inventory_approval', 'Inventory\InventoryApprovalController');
    Route::resource('inventory_approval_district', 'Inventory\InventoryApprovalDistrictController');
    Route::resource('inventory_delivery_pre_census', 'Inventory\InventoryDeliveryPreCensusController');
    Route::resource('inventory_delivery_post_census', 'Inventory\InventoryDeliveryPostCensusController');
    Route::resource('inventory_acceptance_pre_census', 'Inventory\InventoryAcceptancePreCensusController');
    Route::resource('inventory_acceptance_post_census', 'Inventory\InventoryAcceptancePostCensusController');
    Route::resource('inventory_store_record', 'Inventory\InventoryStoreRecordController');
    Route::resource('inventory_tracking', 'Inventory\InventoryTrackingController');
    Route::resource('inventory_tracking_state', 'Inventory\InventoryTrackingStateController');
    Route::resource('inventory_tracking_admin', 'Inventory\InventoryTrackingDistrictAdminController');
    Route::resource('inventory_tracking_district', 'Inventory\InventoryTrackingDistrictController');
    Route::resource('inventory_tracking_eb', 'Inventory\InventoryTrackingEBController');
    Route::resource('inventory_tracking_acceptance', 'Inventory\InventoryTrackingAcceptanceController');

    Route::resource('personnel_dashboard', 'Personnel\PersonnelDashboardController');
    Route::resource('personnel', 'Personnel\PersonnelController');
    Route::resource('personnel_recruitment', 'Personnel\PersonnelRecruitmentListController');
    Route::resource('recruitment_interview_invitation', 'Personnel\PersonnelRecruitmentInterviewInvitationController');
    Route::resource('recruitment_interview_result', 'Personnel\PersonnelRecruitmentInterviewResultController');
    Route::resource('recruitment_acceptance', 'Personnel\PersonnelRecruitmentAcceptanceController');
    Route::resource('recruitment_info', 'Personnel\PersonnelRecruitmentInfoController');
    Route::resource('replacement', 'Personnel\PersonnelReplacementController');
});
// Section Pages
Route::view('/sample/error404', 'errors.404')->name('error404');
Route::view('/sample/error500', 'errors.500')->name('error500');

app/Http/Controllers/Personnel/PersonnelController.php
<?php

namespace App\Http\Controllers\Personnel;

class PersonnelController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('personnel.personnel_list');
	}
        
	public function edit() {
		return view('personnel.personnel_edit');
	}
}

app/Http/Controllers/Personnel/PersonnelDashboardController.php
<?php

namespace App\Http\Controllers\Personnel;

class PersonnelDashboardController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('personnel.personnel_dashboard');
	}
}

app/Http/Controllers/Personnel/PersonnelRecruitmentAcceptanceController.php
<?php

namespace App\Http\Controllers\Personnel;

class PersonnelRecruitmentAcceptanceController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('personnel.recruitment_acceptance');
	}
        
	public function edit() {
		return view('personnel.recruitment_acceptance_edit');
	}
}

app/Http/Controllers/Personnel/PersonnelRecruitmentInfoController.php
<?php

namespace App\Http\Controllers\Personnel;

class PersonnelRecruitmentInfoController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('personnel.recruitment_info');
	}
}

app/Http/Controllers/Personnel/PersonnelRecruitmentInterviewInvitationController.php
<?php

namespace App\Http\Controllers\Personnel;

class PersonnelRecruitmentInterviewInvitationController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('personnel.recruitment_interview_invitation');
	}
        
	public function edit() {
		return view('personnel.recruitment_interview_invitation_edit');
	}
}

app/Http/Controllers/Personnel/PersonnelRecruitmentInterviewResultController.php
<?php

namespace App\Http\Controllers\Personnel;

class PersonnelRecruitmentInterviewResultController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('personnel.recruitment_interview_result');
	}
        
	public function edit() {
		return view('personnel.recruitment_interview_result_edit');
	}
}

app/Http/Controllers/Personnel/PersonnelRecruitmentListController.php
<?php

namespace App\Http\Controllers\Personnel;

class PersonnelRecruitmentListController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('personnel.recruitment_list');
	}
        
	public function edit() {
		return view('personnel.personnel_edit');
	}
}

app/Http/Controllers/Personnel/PersonnelReplacementController.php
<?php

namespace App\Http\Controllers\Personnel;

class PersonnelReplacementController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('personnel.replacement');
	}
}

resources/views/personnel/personnel_dashboard.blade.php
@extends('master')
@section('content')

<div class="container-fluid">

    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-7">
                <canvas id="pembanci_negeri"  height="200"></canvas>
            </div>
            <div class="col-sm-5">
                <canvas id="pie_pembanci"  height="200"></canvas>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-7">
                <canvas id="penyelia_negeri"  height="200"></canvas>
            </div>
            <div class="col-sm-5">
                <canvas id="pie_penyelia"  height="200"></canvas>
            </div>
        </div>
    </div>

</div>
@endsection
<!-- /.conainer-fluid -->

@section('myscript')
<script src="{{ asset('js/views/personnel_dashboard_barchart.js') }}"></script>
<script src="{{ asset('js/views/personnel_dashboard_piechart.js') }}"></script>
@endsection

resources/views/personnel/recruitment_acceptance.blade.php
@extends('master')
@section('content')

<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-2">
                <div class="card">
                    <div class="card-body">JOHOR</div>
                </div>
                <div class="card">
                    <div class="card-body">5000<br/>Jumlah Calon Memohon</div>
                </div>
                <div class="card">
                    <div class="card-body">3000<br/>Jumlah Lelaki</div>
                </div>
                <div class="card">
                    <div class="card-body">2000<br/>Jumlah Perempuan</div>
                </div>
                <div class="card">
                    <div class="card-body">5000<br/>Jumlah Pemohon Jawatan Penyelia</div>
                </div>
                <div class="card">
                    <div class="card-body">5000<br/>Jumlah Personel Jawatan Pembanci</div>
                </div>

            </div>
            <!-- /.col-->
            <div class="col-lg-10">
                <div class="card">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i> Pengambilan Personel
                    </div>
                    <div class="card-body">
                        <ul class="nav nav-tabs">
                            <li class="nav-item">
                                <a class="nav-link " href="{{ route('personnel_recruitment.index') }}">Senarai Calon</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('recruitment_interview_invitation.index') }}">Jemputan Temuduga</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('recruitment_interview_result.index') }}">Keputusan Temuduga</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="{{ route('recruitment_acceptance.index') }}">Calon Bersetuju</a>
                            </li>
                        </ul>
                        <br/>
                        <div class="row">
                            <div class="col-md-2">
                                <select class="form-control form-control-sm" id="select3" name="select3">
                                    <option value="0">Negeri</option>
                                    <option value="1">Option #1</option>
                                    <option value="2">Option #2</option>
                                    <option value="3">Option #3</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <select class="form-control form-control-sm" id="select3" name="select3">
                                    <option value="0">Daerah Pentadbiran</option>
                                    <option value="1">Option #1</option>
                                    <option value="2">Option #2</option>
                                    <option value="3">Option #3</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <select class="form-control form-control-sm" id="select3" name="select3">
                                    <option value="0">Daerah Banci</option>
                                    <option value="1">Option #1</option>
                                    <option value="2">Option #2</option>
                                    <option value="3">Option #3</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <select class="form-control form-control-sm" id="select3" name="select3">
                                    <option value="0">Pembanci</option>
                                    <option value="1">Option #1</option>
                                    <option value="2">Option #2</option>
                                    <option value="3">Option #3</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                &nbsp;
                            </div>
                            <div class="col-md-2">
                                <button class="btn btn-block btn-primary">Cari</button>
                            </div>
                        </div>
                        <br/>
                        <table class="table table-responsive-sm table-sm">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>No K/P</th>
                                    <th>No Telefon</th>
                                    <th>Email</th>
                                    <th>Jawatan Dipohon</th>
                                    <th>Status</th>
                                    <th>Tindakan</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>Abu</td>
                                    <td>821923-01-9920</td>
                                    <td>0129929233</td>
                                    <td>abu@gmail.com</td>
                                    <td>Pembanci</td>
                                    <td>  <select class="form-control form-control-sm" id="select3" name="select3">
                                            <option value="0">Terima</option>
                                            <option value="1">Option #1</option>
                                            <option value="2">Option #2</option>
                                            <option value="3">Option #3</option>
                                        </select>
                                    </td>
                                    <td><i class="fa fa-search"></i></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <center>
                        <button class="btn btn-primary" type="submit">Hantar</button>
                    </center>
                    <br/>
                </div>
            </div>
            <!-- /.col-->
        </div>
        @endsection
        <!-- /.conainer-fluid -->

resources/views/personnel/recruitment_list.blade.php
@extends('master')
@section('content')

<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-2">
                <div class="card">
                    <div class="card-body">JOHOR</div>
                </div>
                <div class="card">
                    <div class="card-body">5000<br/>Jumlah Calon Memohon</div>
                </div>
                <div class="card">
                    <div class="card-body">3000<br/>Jumlah Lelaki</div>
                </div>
                <div class="card">
                    <div class="card-body">2000<br/>Jumlah Perempuan</div>
                </div>
                <div class="card">
                    <div class="card-body">5000<br/>Jumlah Pemohon Jawatan Penyelia</div>
                </div>
                <div class="card">
                    <div class="card-body">5000<br/>Jumlah Personel Jawatan Pembanci</div>
                </div>

            </div>
            <!-- /.col-->
            <div class="col-lg-10">
                <div class="row">
                    <div class="col-md-8">
                        &nbsp;
                    </div>
                    <div class="col-md-4 input-group">
                        <input class="form-control" id="input1-group2" type="text" name="input1-group2" placeholder="Carian">
                        <span class="input-group-prepend">
                            <button class="btn btn-primary" type="button">
                                <i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </div>
                <br/>
                <div class="card">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i> Pengambilan Personel
                    </div>
                    <div class="card-body">
                        <ul class="nav nav-tabs">
                            <li class="nav-item">
                                <a class="nav-link active" href="{{ route('personnel_recruitment.index') }}">Senarai Calon</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('recruitment_interview_invitation.index') }}">Jemputan Temuduga</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('recruitment_interview_result.index') }}">Keputusan Temuduga</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('recruitment_acceptance.index') }}">Calon Bersetuju</a>
                            </li>
                        </ul>
                        <br/>
                        <div class="row">
                            <div class="col-md-2">
                                <select class="form-control form-control-sm" id="select3" name="select3">
                                    <option value="0">Negeri</option>
                                    <option value="1">Option #1</option>
                                    <option value="2">Option #2</option>
                                    <option value="3">Option #3</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <select class="form-control form-control-sm" id="select3" name="select3">
                                    <option value="0">Daerah Pentadbiran</option>
                                    <option value="1">Option #1</option>
                                    <option value="2">Option #2</option>
                                    <option value="3">Option #3</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <select class="form-control form-control-sm" id="select3" name="select3">
                                    <option value="0">Daerah Banci</option>
                                    <option value="1">Option #1</option>
                                    <option value="2">Option #2</option>
                                    <option value="3">Option #3</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <select class="form-control form-control-sm" id="select3" name="select3">
                                    <option value="0">Pembanci</option>
                                    <option value="1">Option #1</option>
                                    <option value="2">Option #2</option>
                                    <option value="3">Option #3</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                               &nbsp;
                            </div>
                            <div class="col-md-2">
                                <button class="btn btn-block btn-primary">Cari</button>
                            </div>
                        </div>
                        <br/>
                        <table class="table table-responsive-sm table-sm">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>No K/P</th>
                                    <th>No Telefon</th>
                                    <th>Email</th>
                                    <th>Jawatan Dipohon</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td><a href="{{ route('recruitment_info.index') }}">Abu</a></td>
                                    <td>821923-01-9920</td>
                                    <td>0129929233</td>
                                    <td>abu@gmail.com</td>
                                    <td>Pembanci</td>
                                    <td>Calon</td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.col-->
        </div>
        @endsection
        <!-- /.conainer-fluid -->