routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Auth::routes();
/* CoreUI templates */

Route::middleware('auth')->group(function ()
{
    Route::resource('/', 'DashboardController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('document_management', 'Document\DocumentManagementController');
    Route::resource('document_planning', 'Document\DocumentPlanningController');
    Route::resource('document_request', 'Document\DocumentRequestController');
    Route::resource('document_request_district', 'Document\DocumentRequestDistrictController');
    Route::resource('document_approval', 'Document\DocumentApprovalController');
    Route::resource('document_approval_district', 'Document\DocumentApprovalDistrictController');
    Route::resource('document_delivery_pre_census', 'Document\DocumentDeliveryPreCensusController');
    Route::resource('document_delivery_post_census', 'Document\DocumentDeliveryPostCensusController');
    Route::resource('document_acceptance_pre_census', 'Document\DocumentAcceptancePreCensusController');
    Route::resource('document_acceptance_post_census', 'Document\DocumentAcceptancePostCensusController');
    Route::resource('document_store_record', 'Document\DocumentStoreRecordController');
    Route::resource('document_tracking', 'Document\DocumentTrackingController');
    Route::resource('document_tracking_state', 'Document\DocumentTrackingStateController');
    Route::resource('document_tracking_district_admin', 'Document\DocumentTrackingDistrictAdminController');
    Route::resource('document_tracking_district', 'Document\DocumentTrackingDistrictController');
    Route::resource('document_tracking_eb', 'Document\DocumentTrackingEBController');
    Route::resource('document_tracking_acceptance', 'Document\DocumentTrackingAcceptanceController');



    Route::resource('vendor_dashboard', 'Vendor\VendorDashboardController');
    Route::resource('vendor_list', 'Vendor\VendorListController');
    Route::resource('vendor_management', 'Vendor\VendorManagementController');
    Route::resource('vendor_management_btype', 'Vendor\VendorManagementBTypeController');

    Route::resource('asset_management', 'Asset\AssetManagementController');
    Route::resource('asset_planning', 'Asset\AssetPlanningController');
    Route::resource('asset_request', 'Asset\AssetRequestController');
    Route::resource('asset_request_district', 'Asset\AssetRequestDistrictController');
    Route::resource('asset_approval', 'Asset\AssetApprovalController');
    Route::resource('asset_approval_district', 'Asset\AssetApprovalDistrictController');
    Route::resource('asset_delivery_pre_census', 'Asset\AssetDeliveryPreCensusController');
    Route::resource('asset_delivery_post_census', 'Asset\AssetDeliveryPostCensusController');
    Route::resource('asset_acceptance_pre_census', 'Asset\AssetAcceptancePreCensusController');
    Route::resource('asset_acceptance_post_census', 'Asset\AssetAcceptancePostCensusController');
    Route::resource('asset_store_record', 'Asset\AssetStoreRecordController');
    Route::resource('asset_tracking', 'Asset\AssetTrackingController');
    Route::resource('asset_tracking_state', 'Asset\AssetTrackingStateController');
    Route::resource('asset_tracking_district_admin', 'Asset\AssetTrackingDistrictAdminController');
    Route::resource('asset_tracking_district', 'Asset\AssetTrackingDistrictController');
    Route::resource('asset_tracking_eb', 'Asset\AssetTrackingEBController');
    Route::resource('asset_tracking_acceptance', 'Asset\AssetTrackingAcceptanceController');

    Route::resource('inventory_management', 'Inventory\InventoryManagementController');
    Route::resource('inventory_planning', 'Inventory\InventoryPlanningController');
    Route::resource('inventory_request', 'Inventory\InventoryRequestController');
    Route::resource('inventory_request_district', 'Inventory\InventoryRequestDistrictController');
    Route::resource('inventory_approval', 'Inventory\InventoryApprovalController');
    Route::resource('inventory_approval_district', 'Inventory\InventoryApprovalDistrictController');
    Route::resource('inventory_delivery_pre_census', 'Inventory\InventoryDeliveryPreCensusController');
    Route::resource('inventory_delivery_post_census', 'Inventory\InventoryDeliveryPostCensusController');
    Route::resource('inventory_acceptance_pre_census', 'Inventory\InventoryAcceptancePreCensusController');
    Route::resource('inventory_acceptance_post_census', 'Inventory\InventoryAcceptancePostCensusController');
    Route::resource('inventory_store_record', 'Inventory\InventoryStoreRecordController');
    Route::resource('inventory_tracking', 'Inventory\InventoryTrackingController');
    Route::resource('inventory_tracking_state', 'Inventory\InventoryTrackingStateController');
    Route::resource('inventory_tracking_admin', 'Inventory\InventoryTrackingDistrictAdminController');
    Route::resource('inventory_tracking_district', 'Inventory\InventoryTrackingDistrictController');
    Route::resource('inventory_tracking_eb', 'Inventory\InventoryTrackingEBController');
    Route::resource('inventory_tracking_acceptance', 'Inventory\InventoryTrackingAcceptanceController');

    Route::resource('personnel_dashboard', 'Personnel\PersonnelDashboardController');
    Route::resource('personnel', 'Personnel\PersonnelController');
    Route::resource('personnel_recruitment', 'Personnel\PersonnelRecruitmentListController');
    Route::resource('recruitment_interview_invitation', 'Personnel\PersonnelRecruitmentInterviewInvitationController');
    Route::resource('recruitment_interview_result', 'Personnel\PersonnelRecruitmentInterviewResultController');
    Route::resource('recruitment_acceptance', 'Personnel\PersonnelRecruitmentAcceptanceController');
    Route::resource('recruitment_info', 'Personnel\PersonnelRecruitmentInfoController');
    Route::resource('replacement', 'Personnel\PersonnelReplacementController');
});
// Section Pages
Route::view('/sample/error404', 'errors.404')->name('error404');
Route::view('/sample/error500', 'errors.500')->name('error500');

app/Http/Controllers/Inventory/InventoryAcceptancePostCensusController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryAcceptancePostCensusController extends \App\Http\Controllers\Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        
    }



    /**
     * Create the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('inventory.inventory_delivery_post_census_create');
    }



}

app/Http/Controllers/Inventory/InventoryAcceptancePreCensusController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryAcceptancePreCensusController extends \App\Http\Controllers\Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        
    }

    /**
     * Create the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('inventory.inventory_delivery_pre_census_create');
    }

}

app/Http/Controllers/Inventory/InventoryApprovalController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryApprovalController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_approval');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('inventory.inventory_approval_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('inventory.inventory_approval_edit');
	}
}

app/Http/Controllers/Inventory/InventoryApprovalDistrictController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryApprovalDistrictController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_approval_district');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('inventory.inventory_approval_district_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('inventory.inventory_approval_district_edit');
	}
}

app/Http/Controllers/Inventory/InventoryDeliveryPostCensusController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryDeliveryPostCensusController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('inventory.inventory_delivery_post_census_create');
	}
}

app/Http/Controllers/Inventory/InventoryDeliveryPreCensusController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryDeliveryPreCensusController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */

	public function create() {
		return view('inventory.inventory_delivery_pre_census_create');
	}
}

app/Http/Controllers/Inventory/InventoryManagementController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryManagementController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_management');
	}
	
	public function create() {
		return view('inventory.inventory_management_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('inventory.inventory_management_edit');
	}
}

app/Http/Controllers/Inventory/InventoryPlanningController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryPlanningController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_planning');
	}
}

app/Http/Controllers/Inventory/InventoryRequestController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryRequestController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_request');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('inventory.inventory_request_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('inventory.inventory_request_edit');
	}
}

app/Http/Controllers/Inventory/InventoryRequestDistrictController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryRequestDistrictController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_request_district');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('inventory.inventory_request_district_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('inventory.inventory_request_district_edit');
	}
}

app/Http/Controllers/Inventory/InventoryStoreRecordController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryStoreRecordController extends \App\Http\Controllers\Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        
    }



    /**
     * Create the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('inventory.inventory_store_record_create');
    }



}

app/Http/Controllers/Inventory/InventoryTrackingAcceptanceController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryTrackingAcceptanceController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_tracking_acceptance');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('inventory.inventory_tracking_acceptance_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('inventory.inventory_tracking_acceptance_edit');
	}
}

app/Http/Controllers/Inventory/InventoryTrackingController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryTrackingController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_tracking');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('inventory.inventory_tracking_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('inventory.inventory_tracking_edit');
	}
}

app/Http/Controllers/Inventory/InventoryTrackingDistrictAdminController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryTrackingDistrictAdminController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_tracking_admin');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('inventory.inventory_tracking_admin_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('inventory.inventory_tracking_admin_edit');
	}
}

app/Http/Controllers/Inventory/InventoryTrackingDistrictController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryTrackingDistrictController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_tracking_district_census');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('inventory.inventory_tracking_district_census_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('inventory.inventory_tracking_district_census_edit');
	}
}

app/Http/Controllers/Inventory/InventoryTrackingStateController.php
<?php

namespace App\Http\Controllers\Inventory;

class InventoryTrackingStateController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('inventory.inventory_tracking_state');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('inventory.inventory_tracking_state_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('inventory.inventory_tracking_state_edit');
	}
}

resources/views/inventory/inventory_request_by_district.blade.php
@extends('master')
@section('content')

<div class="container-fluid">
    <div class="row">

        <div class="col-sm-4 col-lg-4">
            <div class="col-xs-12 text-center ">
                <input type="text" class="form-control" placeholder="Cari nama dokumen" />
                <br/>
                <h6>Maklumat Baki Inventori Setiap Daerah</h6>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8 col-lg-8">
            <div class="card">
                <div class="card-header">
                    Permintaan Inventori Bagi Daerah</div>
                <div class="card-body">
                    <a href="{{route('inventory_request_district.create')}}" class="btn btn-primary">Permintaan</a>
                    <table class="table table-sm table-responsive-lg table-responsive-sm">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Tarikh Permintaan</th>
                                <th>Kod Inventori</th>
                                <th>Nama Inventori</th>
                                <th>Daerah Pemohon</th>
                                <th>Daerah Dipohon</th>
                                <th>Kuantiti</th>
                                <th>Status</th>
                                <th>Tindakan</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>30/09/2018</td>
                                <td>2</td>
                                <td>Soal Selidik</td>
                                <td>Johor Bahru</td>
                                <td>Alor Gajah</td>
                                <td>100</td>
                                <td>
                                    <span class="badge badge-info">Lulus</span>
                                </td>
                                <td>
                                    <i class="icon-pencil" />
                                    <i class="icon-trash" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link" href="#">Prev</a>
                        </li>
                        <li class="page-item active">
                            <a class="page-link" href="#">1</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">2</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">3</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">4</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<!-- /.conainer-fluid -->

resources/views/inventory/inventory_request_by_district_create.blade.php
@extends('master')
@section('content')

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <strong>Credit Card</strong>
            <small>Form</small>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input class="form-control" id="name" type="text" placeholder="Enter your name">
                    </div>
                </div>
            </div>
            <!-- /.row-->
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="ccnumber">Credit Card Number</label>
                        <input class="form-control" id="ccnumber" type="text" placeholder="0000 0000 0000 0000">
                    </div>
                </div>
            </div>
            <!-- /.row-->
            <div class="row">
                <div class="form-group col-sm-4">
                    <label for="ccmonth">Month</label>
                    <select class="form-control" id="ccmonth">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                    </select>
                </div>
                <div class="form-group col-sm-4">
                    <label for="ccyear">Year</label>
                    <select class="form-control" id="ccyear">
                        <option>2014</option>
                        <option>2015</option>
                        <option>2016</option>
                        <option>2017</option>
                        <option>2018</option>
                        <option>2019</option>
                        <option>2020</option>
                        <option>2021</option>
                        <option>2022</option>
                        <option>2023</option>
                        <option>2024</option>
                        <option>2025</option>
                    </select>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="cvv">CVV/CVC</label>
                        <input class="form-control" id="cvv" type="text" placeholder="123">
                    </div>
                </div>
            </div>
            <!-- /.row-->
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Permintaan Inventori Bagi Daerah</div>
        <div class="card-body">
            <a href="{{route('inventory_request_district.create')}}" class="btn btn-primary">Permintaan</a>
            <table class="table table-sm table-responsive-lg table-responsive-sm">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Tarikh Permintaan</th>
                        <th>Kod Inventori</th>
                        <th>Nama Inventori</th>
                        <th>Daerah Pemohon</th>
                        <th>Daerah Dipohon</th>
                        <th>Kuantiti</th>
                        <th>Status</th>
                        <th>Tindakan</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>30/09/2018</td>
                        <td>2</td>
                        <td>Soal Selidik</td>
                        <td>Johor Bahru</td>
                        <td>Alor Gajah</td>
                        <td>100</td>
                        <td>
                            <span class="badge badge-info">Lulus</span>
                        </td>
                        <td>
                            <i class="icon-pencil" />
                            <i class="icon-trash" />
                        </td>
                    </tr>
                </tbody>
            </table>
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="#">Prev</a>
                </li>
                <li class="page-item active">
                    <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">2</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">3</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">4</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </div>
    </div>
</div>
@endsection
<!-- /.conainer-fluid -->