routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Auth::routes();
/* CoreUI templates */

Route::middleware('auth')->group(function ()
{
    Route::resource('/', 'DashboardController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('document_management', 'Document\DocumentManagementController');
    Route::resource('document_planning', 'Document\DocumentPlanningController');
    Route::resource('document_request', 'Document\DocumentRequestController');
    Route::resource('document_request_district', 'Document\DocumentRequestDistrictController');
    Route::resource('document_approval', 'Document\DocumentApprovalController');
    Route::resource('document_approval_district', 'Document\DocumentApprovalDistrictController');
    Route::resource('document_delivery_pre_census', 'Document\DocumentDeliveryPreCensusController');
    Route::resource('document_delivery_post_census', 'Document\DocumentDeliveryPostCensusController');
    Route::resource('document_acceptance_pre_census', 'Document\DocumentAcceptancePreCensusController');
    Route::resource('document_acceptance_post_census', 'Document\DocumentAcceptancePostCensusController');
    Route::resource('document_store_record', 'Document\DocumentStoreRecordController');
    Route::resource('document_tracking', 'Document\DocumentTrackingController');
    Route::resource('document_tracking_state', 'Document\DocumentTrackingStateController');
    Route::resource('document_tracking_district_admin', 'Document\DocumentTrackingDistrictAdminController');
    Route::resource('document_tracking_district', 'Document\DocumentTrackingDistrictController');
    Route::resource('document_tracking_eb', 'Document\DocumentTrackingEBController');
    Route::resource('document_tracking_acceptance', 'Document\DocumentTrackingAcceptanceController');



    Route::resource('vendor_dashboard', 'Vendor\VendorDashboardController');
    Route::resource('vendor_list', 'Vendor\VendorListController');
    Route::resource('vendor_management', 'Vendor\VendorManagementController');
    Route::resource('vendor_management_btype', 'Vendor\VendorManagementBTypeController');

    Route::resource('asset_management', 'Asset\AssetManagementController');
    Route::resource('asset_planning', 'Asset\AssetPlanningController');
    Route::resource('asset_request', 'Asset\AssetRequestController');
    Route::resource('asset_request_district', 'Asset\AssetRequestDistrictController');
    Route::resource('asset_approval', 'Asset\AssetApprovalController');
    Route::resource('asset_approval_district', 'Asset\AssetApprovalDistrictController');
    Route::resource('asset_delivery_pre_census', 'Asset\AssetDeliveryPreCensusController');
    Route::resource('asset_delivery_post_census', 'Asset\AssetDeliveryPostCensusController');
    Route::resource('asset_acceptance_pre_census', 'Asset\AssetAcceptancePreCensusController');
    Route::resource('asset_acceptance_post_census', 'Asset\AssetAcceptancePostCensusController');
    Route::resource('asset_store_record', 'Asset\AssetStoreRecordController');
    Route::resource('asset_tracking', 'Asset\AssetTrackingController');
    Route::resource('asset_tracking_state', 'Asset\AssetTrackingStateController');
    Route::resource('asset_tracking_district_admin', 'Asset\AssetTrackingDistrictAdminController');
    Route::resource('asset_tracking_district', 'Asset\AssetTrackingDistrictController');
    Route::resource('asset_tracking_eb', 'Asset\AssetTrackingEBController');
    Route::resource('asset_tracking_acceptance', 'Asset\AssetTrackingAcceptanceController');

    Route::resource('inventory_management', 'Inventory\InventoryManagementController');
    Route::resource('inventory_planning', 'Inventory\InventoryPlanningController');
    Route::resource('inventory_request', 'Inventory\InventoryRequestController');
    Route::resource('inventory_request_district', 'Inventory\InventoryRequestDistrictController');
    Route::resource('inventory_approval', 'Inventory\InventoryApprovalController');
    Route::resource('inventory_approval_district', 'Inventory\InventoryApprovalDistrictController');
    Route::resource('inventory_delivery_pre_census', 'Inventory\InventoryDeliveryPreCensusController');
    Route::resource('inventory_delivery_post_census', 'Inventory\InventoryDeliveryPostCensusController');
    Route::resource('inventory_acceptance_pre_census', 'Inventory\InventoryAcceptancePreCensusController');
    Route::resource('inventory_acceptance_post_census', 'Inventory\InventoryAcceptancePostCensusController');
    Route::resource('inventory_store_record', 'Inventory\InventoryStoreRecordController');
    Route::resource('inventory_tracking', 'Inventory\InventoryTrackingController');
    Route::resource('inventory_tracking_state', 'Inventory\InventoryTrackingStateController');
    Route::resource('inventory_tracking_admin', 'Inventory\InventoryTrackingDistrictAdminController');
    Route::resource('inventory_tracking_district', 'Inventory\InventoryTrackingDistrictController');
    Route::resource('inventory_tracking_eb', 'Inventory\InventoryTrackingEBController');
    Route::resource('inventory_tracking_acceptance', 'Inventory\InventoryTrackingAcceptanceController');

    Route::resource('personnel_dashboard', 'Personnel\PersonnelDashboardController');
    Route::resource('personnel', 'Personnel\PersonnelController');
    Route::resource('personnel_recruitment', 'Personnel\PersonnelRecruitmentListController');
    Route::resource('recruitment_interview_invitation', 'Personnel\PersonnelRecruitmentInterviewInvitationController');
    Route::resource('recruitment_interview_result', 'Personnel\PersonnelRecruitmentInterviewResultController');
    Route::resource('recruitment_acceptance', 'Personnel\PersonnelRecruitmentAcceptanceController');
    Route::resource('recruitment_info', 'Personnel\PersonnelRecruitmentInfoController');
    Route::resource('replacement', 'Personnel\PersonnelReplacementController');
});
// Section Pages
Route::view('/sample/error404', 'errors.404')->name('error404');
Route::view('/sample/error500', 'errors.500')->name('error500');

app/Http/Controllers/Api/DocumentController.php
<?php

namespace App\Http\Controllers\Api;

use Freshbitsweb\Laratables\Laratables;

class DocumentController extends \App\Http\Controllers\Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Laratables::recordsOf(\App\User::class);

    }

}

app/Http/Controllers/Document/DocumentAcceptancePostCensusController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentAcceptancePostCensusController extends \App\Http\Controllers\Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        
    }



    /**
     * Create the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('document.document_delivery_post_census_create');
    }



}

app/Http/Controllers/Document/DocumentAcceptancePreCensusController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentAcceptancePreCensusController extends \App\Http\Controllers\Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        
    }

    /**
     * Create the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('document.document_delivery_pre_census_create');
    }

}

app/Http/Controllers/Document/DocumentApprovalController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentApprovalController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('document.document_approval');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('document.document_approval_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('document.document_approval_edit');
	}
}

app/Http/Controllers/Document/DocumentApprovalDistrictController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentApprovalDistrictController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('document.document_approval_district');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('document.document_approval_district_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('document.document_approval_district_edit');
	}
}

app/Http/Controllers/Document/DocumentDeliveryPostCensusController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentDeliveryPostCensusController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('document.document_delivery_post_census_create');
	}
}

app/Http/Controllers/Document/DocumentDeliveryPreCensusController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentDeliveryPreCensusController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */

	public function create() {
		return view('document.document_delivery_pre_census_create');
	}
}

app/Http/Controllers/Document/DocumentManagementController.php
<?php

namespace App\Http\Controllers\Document;

use Illuminate\Http\Request;

class DocumentManagementController extends \App\Http\Controllers\Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
        return view('document.document_management');
    }

    public function create()
    {
        return view('document.document_management_create');
    }

    public function store(\App\Http\Requests\StoreDocument $request)
    {
        //logic
        //model
    }

    /**
     * Edit the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        return view('document.document_management_edit');
    }

}

app/Http/Controllers/Document/DocumentPlanningController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentPlanningController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('document.document_planning');
	}
}

app/Http/Controllers/Document/DocumentRequestController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentRequestController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('document.document_request');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('document.document_request_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('document.document_request_edit');
	}
}

app/Http/Controllers/Document/DocumentRequestDistrictController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentRequestDistrictController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('document.document_request_district');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('document.document_request_district_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('document.document_request_district_edit');
	}
}

app/Http/Controllers/Document/DocumentStoreRecordController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentStoreRecordController extends \App\Http\Controllers\Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        
    }



    /**
     * Create the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('document.document_store_record_create');
    }



}

app/Http/Controllers/Document/DocumentTrackingAcceptanceController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentTrackingAcceptanceController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('document.document_tracking_acceptance');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('document.document_tracking_acceptance_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('document.document_tracking_acceptance_edit');
	}
}

app/Http/Controllers/Document/DocumentTrackingController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentTrackingController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('document.document_tracking');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('document.document_tracking_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('document.document_tracking_edit');
	}
}

app/Http/Controllers/Document/DocumentTrackingDistrictAdminController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentTrackingDistrictAdminController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('document.document_tracking_district_admin');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('document.document_tracking_district_admin_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('document.document_tracking_district_admin_edit');
	}
}

app/Http/Controllers/Document/DocumentTrackingDistrictController.php
<?php

namespace App\Http\Controllers\Document;

class DocumentTrackingDistrictController extends \App\Http\Controllers\Controller {
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct() {
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('document.document_tracking_district_census');
	}

	/**
	 * Create the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('document.document_tracking_district_census_create');
	}

	/**
	 * Edit the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit() {
		return view('document.document_tracking_district_census_edit');
	}
}

resources/views/document/document_disposal.blade.php
@extends('master')
@section('content')

<div class="container-fluid" style="background-color: white;">
    <div style="font-size: 24px;font-weight: bold;">Perlupusan Dokumen</div><br>
    
    <table class="table table-responsive-sm">
        <thead>
            <tr style="background-color: #43B6D7;">
                <th>No Dokumen</th>
                <th>Nama Dokumen</th>
                <th>Tindakan</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Contoh Dokumen</td>
                <td>
                    <a href="document_disposal/edit" style="background-color: limegreen; border-color: limegreen;" class="btn btn-primary" role="button">
                        <i class="fa fa-pencil"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <td>2</td>
                <td>Contoh Dokumen</td>
                <td>
                    <a href="document_disposal/edit" style="background-color: limegreen; border-color: limegreen;" class="btn btn-primary" role="button">
                        <i class="fa fa-pencil"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <td>3</td>
                <td>Contoh Dokumen</td>
                <td>
                    <a href="document_disposal/edit" style="background-color: limegreen; border-color: limegreen;" class="btn btn-primary" role="button">
                        <i class="fa fa-pencil"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <td>3a</td>
                <td>Contoh Dokumen</td>
                <td>
                    <a href="document_disposal/edit" style="background-color: limegreen; border-color: limegreen;" class="btn btn-primary" role="button">
                        <i class="fa fa-pencil"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <td>5</td>
                <td>Contoh Dokumen</td>
                <td>
                    <a href="document_disposal/edit" style="background-color: limegreen; border-color: limegreen;" class="btn btn-primary" role="button">
                        <i class="fa fa-pencil"></i>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="#">Prev</a>
        </li>
        <li class="page-item active">
            <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">4</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">Next</a>
        </li>
    </ul>
</div>
@endsection
<!-- /.conainer-fluid -->

resources/views/document/document_disposal_confirmation.blade.php
@extends('master')
@section('content')

<div class="container-fluid" style="background-color: white;">
    <div style="font-size: 24px;font-weight: bold;">Perlupusan Dokumen > Maklumat Dokumen</div><br>
    
    <div class="form-group row">
        <label class="col-md-2 col-form-label" for="select3">Nama Dokumen</label>
            <div class="col-md-4">
                <select class="form-control form-control-sm" id="select3" name="select3">
                    <option value="0">Sila pilih</option>
                    <option value="1">Option #1</option>
                    <option value="2">Option #2</option>
                    <option value="3">Option #3</option>
                </select>
            </div>
        <label class="col-md-2 col-form-label" for="select3">Muatnaik Dokumen</label>
            <div class="col-md-4">
                <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
            </div>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-form-label" for="select3">No Dokumen</label>
            <div class="col-md-4">
                <select class="form-control form-control-sm" id="select3" name="select3">
                    <option value="0">Sila pilih</option>
                    <option value="1">Option #1</option>
                    <option value="2">Option #2</option>
                    <option value="3">Option #3</option>
                </select>
            </div>
        <label class="col-md-2 col-form-label" for="select3">Alamat premis</label>
            <div class="col-md-4">
                <textarea class="form-control" id="alamatpremis" name="textarea-input" rows="5" placeholder=""></textarea>
            </div>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-form-label" for="select3">Pembekal</label>
            <div class="col-md-4">
                <select class="form-control form-control-sm" id="select3" name="select3">
                    <option value="0">Sila pilih</option>
                    <option value="1">Option #1</option>
                    <option value="2">Option #2</option>
                    <option value="3">Option #3</option>
                </select>
            </div>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-form-label" for="select3">Kuantiti</label>
            <div class="col-md-4">
                <input type="text" class="form-control" id="kuantiti">
            </div>
        <label class="col-md-2 col-form-label" for="select3">No LO</label>
            <div class="col-md-4">
                <input type="text" class="form-control" id="nolo">
            </div>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-form-label" for="select3">Jenis Dokumen</label>
            <div class="col-md-4">
                <input type="text" class="form-control" id="jenisdokumen">
            </div>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-form-label" for="select3">Perlupusan</label>
            <div class="col-md-4">
                    <label class="form-check-label">
                        <input type="checkbox" class="form-check-input">
                        <span style="font-size: 11px; color: grey;"><i>Sila klik untuk melupuskan dokumen</i></span>
                    </label>
            </div>
        <label class="col-md-2 col-form-label" for="select3">Baki Dokumen</label>
            <div class="col-md-2">
                <input type="text" class="form-control" id="bakidokumen">
            </div>
    </div>
    <div class="form-group row">
        <label class="col-md-4 col-form-label" for="select3">Sila tinggalkan komen/maklumbalas untuk melupuskan dokumen</label>
            <div class="col-md-6">
                <textarea style="background-color: grey;" class="form-control" id="komenlupus" name="textarea-input" rows="3" placeholder=""></textarea>
            </div>
    </div>
    <div>
        <br>
            <center>
                <button class="btn btn-success" type="submit">Kemaskini</button>
                <button class="btn btn-primary" type="submit">Hantar</button>
            </center>
        <br>
    </div>
</div>
@endsection
<!-- /.conainer-fluid -->

resources/views/document/document_request_by_district.blade.php
@extends('master')
@section('content')

<div class="container-fluid">
    <div class="row">

        <div class="col-sm-4 col-lg-4">
            <div class="col-xs-12 text-center ">
                <input type="text" class="form-control" placeholder="Cari nama dokumen" />
                <br/>
                <h6>Maklumat Baki Dokumen Setiap Daerah</h6>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card bg-light">
                        <div class="text-center card-body pb-0">
                            &nbsp;
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8 col-lg-8">
            <div class="card">
                <div class="card-header">
                    Permintaan Dokumen Bagi Daerah</div>
                <div class="card-body">
                    <a href="{{route('document_request_district.create')}}" class="btn btn-primary">Permintaan</a>
                    <table class="table table-sm table-responsive-lg table-responsive-sm">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Tarikh Permintaan</th>
                                <th>Kod Dokumen</th>
                                <th>Nama Dokumen</th>
                                <th>Daerah Pemohon</th>
                                <th>Daerah Dipohon</th>
                                <th>Kuantiti</th>
                                <th>Status</th>
                                <th>Tindakan</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>30/09/2018</td>
                                <td>2</td>
                                <td>Soal Selidik</td>
                                <td>Johor Bahru</td>
                                <td>Alor Gajah</td>
                                <td>100</td>
                                <td>
                                    <span class="badge badge-info">Lulus</span>
                                </td>
                                <td>
                                    <i class="icon-pencil" />
                                    <i class="icon-trash" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link" href="#">Prev</a>
                        </li>
                        <li class="page-item active">
                            <a class="page-link" href="#">1</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">2</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">3</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">4</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<!-- /.conainer-fluid -->