routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Auth::routes();
/* CoreUI templates */

Route::middleware('auth')->group(function ()
{
    Route::resource('/', 'DashboardController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('document_management', 'Document\DocumentManagementController');
    Route::resource('document_planning', 'Document\DocumentPlanningController');
    Route::resource('document_request', 'Document\DocumentRequestController');
    Route::resource('document_request_district', 'Document\DocumentRequestDistrictController');
    Route::resource('document_approval', 'Document\DocumentApprovalController');
    Route::resource('document_approval_district', 'Document\DocumentApprovalDistrictController');
    Route::resource('document_delivery_pre_census', 'Document\DocumentDeliveryPreCensusController');
    Route::resource('document_delivery_post_census', 'Document\DocumentDeliveryPostCensusController');
    Route::resource('document_acceptance_pre_census', 'Document\DocumentAcceptancePreCensusController');
    Route::resource('document_acceptance_post_census', 'Document\DocumentAcceptancePostCensusController');
    Route::resource('document_store_record', 'Document\DocumentStoreRecordController');
    Route::resource('document_tracking', 'Document\DocumentTrackingController');
    Route::resource('document_tracking_state', 'Document\DocumentTrackingStateController');
    Route::resource('document_tracking_district_admin', 'Document\DocumentTrackingDistrictAdminController');
    Route::resource('document_tracking_district', 'Document\DocumentTrackingDistrictController');
    Route::resource('document_tracking_eb', 'Document\DocumentTrackingEBController');
    Route::resource('document_tracking_acceptance', 'Document\DocumentTrackingAcceptanceController');



    Route::resource('vendor_dashboard', 'Vendor\VendorDashboardController');
    Route::resource('vendor_list', 'Vendor\VendorListController');
    Route::resource('vendor_management', 'Vendor\VendorManagementController');
    Route::resource('vendor_management_btype', 'Vendor\VendorManagementBTypeController');

    Route::resource('asset_management', 'Asset\AssetManagementController');
    Route::resource('asset_planning', 'Asset\AssetPlanningController');
    Route::resource('asset_request', 'Asset\AssetRequestController');
    Route::resource('asset_request_district', 'Asset\AssetRequestDistrictController');
    Route::resource('asset_approval', 'Asset\AssetApprovalController');
    Route::resource('asset_approval_district', 'Asset\AssetApprovalDistrictController');
    Route::resource('asset_delivery_pre_census', 'Asset\AssetDeliveryPreCensusController');
    Route::resource('asset_delivery_post_census', 'Asset\AssetDeliveryPostCensusController');
    Route::resource('asset_acceptance_pre_census', 'Asset\AssetAcceptancePreCensusController');
    Route::resource('asset_acceptance_post_census', 'Asset\AssetAcceptancePostCensusController');
    Route::resource('asset_store_record', 'Asset\AssetStoreRecordController');
    Route::resource('asset_tracking', 'Asset\AssetTrackingController');
    Route::resource('asset_tracking_state', 'Asset\AssetTrackingStateController');
    Route::resource('asset_tracking_district_admin', 'Asset\AssetTrackingDistrictAdminController');
    Route::resource('asset_tracking_district', 'Asset\AssetTrackingDistrictController');
    Route::resource('asset_tracking_eb', 'Asset\AssetTrackingEBController');
    Route::resource('asset_tracking_acceptance', 'Asset\AssetTrackingAcceptanceController');

    Route::resource('inventory_management', 'Inventory\InventoryManagementController');
    Route::resource('inventory_planning', 'Inventory\InventoryPlanningController');
    Route::resource('inventory_request', 'Inventory\InventoryRequestController');
    Route::resource('inventory_request_district', 'Inventory\InventoryRequestDistrictController');
    Route::resource('inventory_approval', 'Inventory\InventoryApprovalController');
    Route::resource('inventory_approval_district', 'Inventory\InventoryApprovalDistrictController');
    Route::resource('inventory_delivery_pre_census', 'Inventory\InventoryDeliveryPreCensusController');
    Route::resource('inventory_delivery_post_census', 'Inventory\InventoryDeliveryPostCensusController');
    Route::resource('inventory_acceptance_pre_census', 'Inventory\InventoryAcceptancePreCensusController');
    Route::resource('inventory_acceptance_post_census', 'Inventory\InventoryAcceptancePostCensusController');
    Route::resource('inventory_store_record', 'Inventory\InventoryStoreRecordController');
    Route::resource('inventory_tracking', 'Inventory\InventoryTrackingController');
    Route::resource('inventory_tracking_state', 'Inventory\InventoryTrackingStateController');
    Route::resource('inventory_tracking_admin', 'Inventory\InventoryTrackingDistrictAdminController');
    Route::resource('inventory_tracking_district', 'Inventory\InventoryTrackingDistrictController');
    Route::resource('inventory_tracking_eb', 'Inventory\InventoryTrackingEBController');
    Route::resource('inventory_tracking_acceptance', 'Inventory\InventoryTrackingAcceptanceController');

    Route::resource('personnel_dashboard', 'Personnel\PersonnelDashboardController');
    Route::resource('personnel', 'Personnel\PersonnelController');
    Route::resource('personnel_recruitment', 'Personnel\PersonnelRecruitmentListController');
    Route::resource('recruitment_interview_invitation', 'Personnel\PersonnelRecruitmentInterviewInvitationController');
    Route::resource('recruitment_interview_result', 'Personnel\PersonnelRecruitmentInterviewResultController');
    Route::resource('recruitment_acceptance', 'Personnel\PersonnelRecruitmentAcceptanceController');
    Route::resource('recruitment_info', 'Personnel\PersonnelRecruitmentInfoController');
    Route::resource('replacement', 'Personnel\PersonnelReplacementController');
});
// Section Pages
Route::view('/sample/error404', 'errors.404')->name('error404');
Route::view('/sample/error500', 'errors.500')->name('error500');

resources/views/panel/breadcrumb.blade.php
<div class="m-3"></div>
{{-- <ol class="breadcrumb">
  <li class="breadcrumb-item">Home</li>
  <li class="breadcrumb-item"><a href="#">Admin</a></li>
  <li class="breadcrumb-item active">Dashboard</li>

  <!-- Breadcrumb Menu-->
  <li class="breadcrumb-menu d-md-down-none">
    <div class="btn-group" role="group" aria-label="Button group">
      <a class="btn" href="#"><i class="icon-speech"></i></a>
      <a class="btn" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
      <a class="btn" href="#"><i class="icon-settings"></i> &nbsp;Settings</a>
    </div>
  </li>
</ol>
 --}}

resources/views/panel/dashboard.blade.php
@extends('master')
@section('content')

<div class="container-fluid">

    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-8">
                <div class="row">
                    <canvas id="document_statistic_by_state"  height="140"></canvas>
                    <button style="display: none" id="document_statistic_by_district_btn"  class="btn btn-primary" >Kembali</button>
                    <canvas style="display: none" id="document_statistic_by_district"  height="140"></canvas>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-light">
                            <div class="card-body pb-0">
                                <canvas height="400" id="pie1" ></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-light">
                            <div class="card-body pb-0">
                                <canvas height="400" id="pie2" ></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-light">
                            <div class="card-body pb-0">
                                <canvas height="400" id="pie3" ></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-light">
                            <div class="card-body pb-0">
                                <canvas height="400" id="pie4" ></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-light">
                            <div class="card-body pb-0">
                                <canvas height="400" id="pie5" ></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-light">
                            <div class="card-body pb-0">
                                <canvas height="400" id="pie6" ></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-light">
                            <div class="card-body pb-0">
                                <canvas height="400" id="pie7" ></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-light">
                            <div class="card-body pb-0">
                                <canvas height="400" id="pie8" ></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <canvas id="inventory_statistic_by_state" height="140"></canvas>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card bg-light">
                            <div class="text-center card-body pb-0">
                                <h3>10,000,000</h3>
                                Dokumen
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="card bg-light">
                            <div class="text-center card-body pb-0">
                                <h3>5,000</h3>
                                Aset
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card bg-light">
                            <div class="text-center card-body pb-0">
                                <h3>10,000</h3>
                                Inventori
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="card bg-light">
                            <div class="text-center card-body pb-0">
                                <h3>3,500</h3>
                                Personel
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card bg-light">
                            <div class="text-center card-body pb-0">
                                <h3>90</h3>
                                Vendor
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="card bg-light">
                            <div class="text-center card-body pb-0">
                                <h3>50</h3>
                                Premis
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <canvas id="personel_stats" height="400"></canvas>
                </div>
            </div>
            <!--/.col-->
        </div>
        <!--/.row-->
    </div>

</div>
@endsection
<!-- /.conainer-fluid -->

@section('myscript')
<script src="{{ asset('js/views/dashboard_dokumen_statistic.js') }}"></script>
<script src="{{ asset('js/views/dashboard_inventory_statistic.js') }}"></script>
<script src="{{ asset('js/views/dashboard_piechart.js') }}"></script>
<script src="{{ asset('js/views/dashboard_personel.js') }}"></script>
@endsection

resources/views/panel/footer.blade.php
<footer class="app-footer">
    <span><a href="http://coreui.io">CoreUI</a> © 2017 creativeLabs.</span>
    <span class="ml-auto">Powered by <a href="http://coreui.io">CoreUI</a></span>
</footer>

resources/views/panel/navbar.blade.php
<header class="app-header navbar">
  <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>

 
  <ul class="nav navbar-nav ml-auto">
    <!--
    <li class="nav-item d-md-down-none">
      <a class="nav-link" href="#"><i class="icon-bell"></i><span class="badge badge-pill badge-danger">5</span></a>
    </li>
    <li class="nav-item d-md-down-none">
      <a class="nav-link" href="#"><i class="icon-list"></i></a>
    </li>
    <li class="nav-item d-md-down-none">
      <a class="nav-link" href="#"><i class="icon-location-pin"></i></a>
    </li>
    -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        @if (Auth::check())
          <img src="https://www.gravatar.com/avatar/{{md5(strtolower(trim(Auth::user()->email)))}}?s=160&d=retro" class="img-avatar" alt="{{ Auth::user()->email }}">
        @else
          <img src="{{ asset('img/avatars/6.jpg') }}" class="img-avatar" alt="admin@bootstrapmaster.com">
        @endif
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-header text-center">
          <strong>{{ auth()->user()->name }}'s Account</strong>
        </div>
{{--         <a class="dropdown-item" href="#"><i class="fa fa-bell-o"></i> Updates<span class="badge badge-info">42</span></a>
        <a class="dropdown-item" href="#"><i class="fa fa-envelope-o"></i> Messages<span class="badge badge-success">42</span></a>
        <a class="dropdown-item" href="#"><i class="fa fa-tasks"></i> Tasks<span class="badge badge-danger">42</span></a>
        <a class="dropdown-item" href="#"><i class="fa fa-comments"></i> Comments<span class="badge badge-warning">42</span></a>
        <div class="dropdown-header text-center">
          <strong>Settings</strong>
        </div>
        <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Profile</a>
        <a class="dropdown-item" href="#"><i class="fa fa-wrench"></i> Settings</a>
        <a class="dropdown-item" href="#"><i class="fa fa-usd"></i> Payments<span class="badge badge-secondary">42</span></a>
        <a class="dropdown-item" href="#"><i class="fa fa-file"></i> Projects<span class="badge badge-primary">42</span></a>
        <div class="divider"></div>
        <a class="dropdown-item" href="#"><i class="fa fa-shield"></i> Lock Account</a>
 --}}        
        <a class="dropdown-item" href="{{ route('logout') }}" 
          onclick="event.preventDefault(); 
          document.getElementById('logout-form').submit();">
          <i class="fa fa-lock"></i> Logout </a>
      </div>
    </li>
  </ul>
  
  <button class="navbar-toggler aside-menu-toggler" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>

 <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
  {{ csrf_field() }}
</form>
</header>

resources/views/panel/scripts.blade.php
<!-- Bootstrap and necessary plugins -->
<script src="{{ asset('js/vendor/jquery.min.js') }}"></script>
<script src="{{ asset('js/vendor/popper.min.js') }}"></script>
<script src="{{ asset('js/vendor/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/vendor/pace.min.js') }}"></script>
<!-- Plugins and scripts required by all views -->
<script src="{{ asset('js/vendor/Chart.min.js') }}"></script>
<!-- CoreUI main scripts -->
<script src="{{ asset('js/app.js')}}"></script>
<script src="{{ url('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
<script type="text/javascript" src="//cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>

resources/views/panel/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-title">
                <a href="{{ route('dashboard.index') }}">CENSUS TRACKING</a>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="icon-doc"></i> DOKUMEN</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            Pengurusan Dokumen</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('document_management.index') }}">
                                     Senarai Dokumen</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('document_planning.index') }}">
                                     Perancangan Dokumen</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('document_request.index') }}">
                                     Permintaan Dokumen</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('document_approval.index') }}">
                            Kelulusan Dokumen</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="{{ route('document_store_record.create') }}">
                            Pengurusan Rekod Stor</a>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            Penghantaran Dokumen</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('document_delivery_pre_census.create') }}">
                                     Pra/Semasa Banci</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('document_delivery_post_census.create') }}">
                                     Pasca Banci</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            Penerimaan Dokumen</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('document_acceptance_pre_census.create') }}">
                                     Pra/Semasa Banci</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('document_acceptance_post_census.create') }}">
                                     Pasca Banci</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('document_tracking.index') }}">
                            Tracking Dokumen</a>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('document_management.index') }}">
                            Pelupusan Dokumen</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="icon-doc"></i> ASET</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            Pengurusan Aset</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('asset_management.index') }}">
                                     Senarai Aset</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('asset_planning.index') }}">
                                     Perancangan Aset</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('asset_request.index') }}">
                                     Permintaan Aset</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('asset_approval.index') }}">
                            Kelulusan Aset</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="{{ route('asset_store_record.create') }}">
                            Pengurusan Rekod Stor</a>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            Penghantaran Aset</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('asset_delivery_pre_census.create') }}">
                                     Pra/Semasa Banci</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('asset_delivery_post_census.create') }}">
                                     Pasca Banci</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            Penerimaan Aset</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('asset_acceptance_pre_census.create') }}">
                                     Pra/Semasa Banci</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('asset_acceptance_post_census.create') }}">
                                     Pasca Banci</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('asset_tracking.index') }}">
                            Tracking Aset</a>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('asset_management.index') }}">
                            Pelupusan Aset</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="icon-doc"></i> INVENTORI</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            Pengurusan Inventori</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('inventory_management.index') }}">
                                     Senarai Inventori</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('inventory_planning.index') }}">
                                     Perancangan Inventori</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('inventory_request.index') }}">
                                     Permintaan Inventori</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('inventory_approval.index') }}">
                            Kelulusan Inventori</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="{{ route('inventory_store_record.create') }}">
                            Pengurusan Rekod Stor</a>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            Penghantaran Inventori</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('inventory_delivery_pre_census.create') }}">
                                     Pra/Semasa Banci</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('inventory_delivery_post_census.create') }}">
                                     Pasca Banci</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            Penerimaan Inventori</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('inventory_acceptance_pre_census.create') }}">
                                     Pra/Semasa Banci</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('inventory_acceptance_post_census.create') }}">
                                     Pasca Banci</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('inventory_tracking.index') }}">
                            Tracking Inventori</a>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('inventory_management.index') }}">
                            Pelupusan Inventori</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="icon-user"></i> PERSONEL</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('personnel_dashboard.index') }}">
                            Dashboard</a>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            Pengurusan Personel</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('personnel.index') }}">
                                     Senarai Personel</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('personnel_recruitment.index') }}">
                                     Pengambilan Personel</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link " href="{{ route('replacement.index') }}">
                            Penggantian/Penamatan</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="icon-grid"></i> VENDOR</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('vendor_management.index') }}">
                            Pengurusan Vendor</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="icon-home"></i> PREMIS</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            Pengurusan Premis</a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>